# Data Directory
data_path = "data/"

# eGo^n Files
egon_files = ["eGon-data.grid.hvmv_substation.gpkg", "eGon-data.grid.mv_grid_district.gpkg"]
egon_epsg = 3035

# BAST Files
bast_file = "BAST2019.csv"
relevant_columns = ["DTV_SV_MobisSo_Q", "Koor_WGS84_E", "Koor_WGS84_N"]
bast_epsg = 4326

# Germany Shapefile
germany_json = "germany_hoch.geo.json"
germany_epsg = 4326

# NEP data
# https://www.netzentwicklungsplan.de/sites/default/files/paragraphs-files/NEP_2035_V2021_2_Entwurf_Teil1.pdf
# total amount of HGVs  - Scenario C 2035
hgv_amount = 100000
# HGV traffic annual mileage per vehicle
hgv_mean_mileage = 100000

# Hydrogen
# HGV traffic hydrogen consumption in kg per 100 km
# Assumption: 30L Diesel / 100 km --> kgH2/100 km
hydrogen_consumption = 6.68

# Output
output_dir = "res/"
output_csv = "{}_hydrogen_consumption_per_mv_grid_district.csv"
output_png = "{}_hydrogen_consumption_per_mv_grid_district.png"